import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Provider";
import { AuthProvider } from "./providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Provider>
          <AuthProvider>
            <main className="page-container">{children}</main>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
